### ISSUE TITLE
Galaxy url fail

### ISSUE THREAD

**Issue by chusiang** [itcraftsmanpl/ansible-role-php7#11]
Hi @itcraftsmanpl ,

Your original galaxy url is fail, maybe you can change to new one.

- Original: https://galaxy.ansible.com/detail#/role/6364
- New: https://galaxy.ansible.com/itcraftsmanpl/php7/

Thank you for your roles, again.

@chusiang

**Comment by akondas** [comment]
Thanks. Link updated.
